/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-06-02 18:26:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao_jdbc.VehicleBrandDAOImpl;
import dao_api.VehicleBrandDAO;
import model.VehicleBrand;
import dao_jdbc.VehicleTypeDAOImpl;
import model.Country;
import dao_jdbc.CountryDAOImpl;
import dao_api.CountryDAO;
import model.InsurerType;
import dao_jdbc.InsurerTypeDAOImpl;
import dao_api.InsurerTypeDAO;
import model.VehicleType;
import dao_api.VehicleTypeDAO;

public final class insurerAddNewGO_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.VehicleBrand");
    _jspx_imports_classes.add("dao_jdbc.VehicleTypeDAOImpl");
    _jspx_imports_classes.add("dao_jdbc.CountryDAOImpl");
    _jspx_imports_classes.add("model.Country");
    _jspx_imports_classes.add("dao_api.VehicleTypeDAO");
    _jspx_imports_classes.add("dao_api.VehicleBrandDAO");
    _jspx_imports_classes.add("dao_jdbc.VehicleBrandDAOImpl");
    _jspx_imports_classes.add("dao_api.InsurerTypeDAO");
    _jspx_imports_classes.add("model.InsurerType");
    _jspx_imports_classes.add("dao_jdbc.InsurerTypeDAOImpl");
    _jspx_imports_classes.add("model.VehicleType");
    _jspx_imports_classes.add("dao_api.CountryDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t");

			String userName = null;
			Cookie[] cookies = request.getCookies();
			if(cookies != null) {
				for(Cookie cookie: cookies) {
					if(cookie.getName().equals("user")) {
						userName = cookie.getValue();
					}
				}
			}
			if(userName == null) {
				response.sendRedirect("login.jsp");
			}
		
      out.write("\r\n");
      out.write("\t\t<title>");
      out.print(userName );
      out.write("</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href = \"style.css\" type=\"text/css\" rel = \"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("\t\t<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t\t<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$( \"#datepicker1\" ).datepicker({\r\n");
      out.write("\t\t\t\t\tdateFormat: \"yy-mm-dd\",\r\n");
      out.write("\t\t\t\t\tonSelect: function(datetext){\r\n");
      out.write("\t\t\t\t\t\t$(this).val(datetext); }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$( \"#datepicker2\" ).datepicker({\r\n");
      out.write("\t\t\t\t\tdateFormat: \"yy-mm-dd\",\r\n");
      out.write("\t\t\t\t\tonSelect: function(datetext){\r\n");
      out.write("\t\t\t\t\t\t$(this).val(datetext); }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction change() {\r\n");
      out.write("\t\t\t\tvar arr = [];\r\n");
      out.write("\t\t\t\tswitch(document.getElementById(\"vehicleType\").value) {\r\n");
      out.write("\t\t\t\tcase 'Автомобил':\r\n");
      out.write("\t\t\t\t\tif(!arr.length) {\r\n");
      out.write("\t\t\t\t\tarr = [\"до 1100 куб см\", \r\n");
      out.write("\t\t\t\t\t           \"от 1101 до 1200 куб см\", \r\n");
      out.write("\t\t\t\t\t           \"от 1201 до 1400 куб см\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"от 1401 до 1600 куб см\", \r\n");
      out.write("\t\t\t\t\t\t\t   \"от 1601 до 1800 куб см\", \r\n");
      out.write("\t\t\t\t\t\t\t   \"от 1801 до 2000 куб см\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"от 2001 до 2200 куб см\", \r\n");
      out.write("\t\t\t\t\t\t\t   \"от 2201 до 2500 куб см\", \r\n");
      out.write("\t\t\t\t\t\t\t   \"над  2500 куб см\", \r\n");
      out.write("\t\t\t\t\t\t\t   \"Електромобил\"];\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"kubici\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\tvar kubici = document.getElementById('kubici');\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t    \toption.text = option.value = arr[i];\r\n");
      out.write("\t\t\t\t    \tkubici.add(option, 0);\r\n");
      out.write("\t\t\t\t\t}}\r\n");
      out.write("\t\t\t\t\tsum();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 'Товарни автомобили':\r\n");
      out.write("\t\t\t\t\tif(!arr.length) {\r\n");
      out.write("\t\t\t\t\tarr = [\"до 0.8 т. включително\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 0.8 до 1.5 т.\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 1,5 до 2.5 т.\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 2,5 до 3.5 т.\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 3,5 до 5,0 т.\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 5,0 до 10 т.\",\r\n");
      out.write("\t\t\t\t \t\t\t   \"над 10  до 20 т.\",\r\n");
      out.write("\t\t\t\t\t\t\t   \"над 20 т.\"];\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"kubici\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\tvar kubici = document.getElementById('kubici');\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t    \toption.text = option.value = arr[i];\r\n");
      out.write("\t\t\t\t    \tkubici.add(option, 0);\r\n");
      out.write("\t\t\t\t\t}}\r\n");
      out.write("\t\t\t\t\tsum();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 'Мотоциклет':\r\n");
      out.write("\t\t\t\t\tif(!arr.length) {\r\n");
      out.write("\t\t\t\t\t\tarr = [\"до 50 куб. см.\",\r\n");
      out.write("\t\t\t\t\t\t       \"над   50 до 125 куб. см\",\r\n");
      out.write("\t\t\t\t\t\t       \"над 125 до 250 куб. см\",\r\n");
      out.write("\t\t\t\t\t\t       \"над 250 до 350 куб. см\",\r\n");
      out.write("\t\t\t\t\t\t       \"над 350 до 490 куб. см\",\r\n");
      out.write("\t\t\t\t\t\t       \"над 490 до 750 куб. см\",\r\n");
      out.write("\t\t\t\t\t\t       \"над 750 куб. см\"];\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"kubici\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\tvar kubici = document.getElementById('kubici');\r\n");
      out.write("\t\t\t\t\t\tfor(var i = 0; i < arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t\t    \toption.text = option.value = arr[i];\r\n");
      out.write("\t\t\t\t\t    \tkubici.add(option, 0);\r\n");
      out.write("\t\t\t\t\t\t}}\r\n");
      out.write("\t\t\t\t\tsum();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 'Автобус':\r\n");
      out.write("\t\t\t\t\tif(!arr.length) {\r\n");
      out.write("\t\t\t\t\tarr = [\"до   20 места включително\",\r\n");
      out.write("\t\t\t\t\t           \"над 20 места до 40 места\",\r\n");
      out.write("\t\t\t\t\t           \"над 40 места\"];\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"kubici\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\tvar kubici = document.getElementById('kubici');\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t    \toption.text = option.value = arr[i];\r\n");
      out.write("\t\t\t\t    \tkubici.add(option, 0);\r\n");
      out.write("\t\t\t\t\t}}\r\n");
      out.write("\t\t\t\t\tsum();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tfunction sum() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=\"\";\r\n");
      out.write("\t\t\t\t\tswitch (document.getElementById(\"kubici\").value) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcase \"до 1100 куб см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=162;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=153;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=147;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 1101 до 1200 куб см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=162;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=153;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=147;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 1201 до 1400 куб см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=162;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=154;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=147;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 1401 до 1600 куб см\": \r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=163;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=155;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=152;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 1601 до 1800 куб см\": \r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=173;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=163;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=153;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 1801 до 2000 куб см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=181;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=164;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=159;\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 2001 до 2200 куб см\": \r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=226;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=210;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=196;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"от 2201 до 2500 куб см\": \r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=226;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=210;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=197;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над  2500 куб см\": \r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=253;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=237;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=225;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"Електромобил\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=163;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=155;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=152;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcase \"до 0.8 т. включително\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=191;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=188;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=185;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 0.8 до 1.5 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=205;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=200;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=195;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 1,5 до 2.5 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=205;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=200;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=195;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 2,5 до 3.5 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=240;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=235;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=230;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tcase \"над 3,5 до 5,0 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=290;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=285;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=280;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 5,0 до 10 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=590;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=585;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=580;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 10  до 20 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=865;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=860;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=855;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 20 т.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=1045;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\") {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=1040;\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=1035;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcase \"до 50 куб. см.\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=85;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над   50 до 125 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=85;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 125 до 250 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=85;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 250 до 350 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=85;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 350 до 490 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t   \t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=85;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=90;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 490 до 750 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t  \t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=95;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=105;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 750 куб. см\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=120;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=130;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcase \"до   20 места включително\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t \t\tdocument.getElementById('vehicleInsValue').value=447;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 20 места до 40 места\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=667;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase \"над 40 места\":\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById('zone').value === \"Зона І - София\" || \r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона IІ - Пловдив, Варна и Бургас\" ||\r\n");
      out.write("\t\t\t\t\t\t   document.getElementById('zone').value === \"Зона ІІІ - Други\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('vehicleInsValue').value=795;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<div class=\"menu-nav\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"insurer.jsp\">Нова застраховка</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"insurerAddNewGO.jsp\">Гражданска отговорност</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"insurerAddNewKasko.jsp\">Каско</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Търсене</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Гражданска отговорност</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchGO.jsp\">Търсене по №</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"seachGOByInsurer.jsp\">Търсене по текущ застраховател</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchGOAll.jsp\">Изведи всички</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Каско</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchInsKaskoByID.jsp\">Търсене по №</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchKaskoByInsurer.jsp\">Търсене по текущ застраховател</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchAllKasko.jsp\">Изведи всички</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"insurerSettings.jsp\">Настройки</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/logout\">Изход</a>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"newGO\">\r\n");
      out.write("\t\t\t<div class=\"shell\">\r\n");
      out.write("\t\t\t\t<h3>Сключване на застраховка \"Гражданеска отговорност\"</h3>\r\n");
      out.write("\t\t\t\t<form action=\"addNewGO\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-section\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Застрахователна полица ГО на МПС</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>№ на полица</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" name=\"policaN\" >\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>Застраховател</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" value=");
      out.print(userName);
      out.write(" name=\"userName\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-section\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Застрахован</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"insType\" class=\"field\" name=\"insType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									InsurerTypeDAO insTypes = new InsurerTypeDAOImpl();
									for(InsurerType type : insTypes.listInsurerTypes()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(type.getInsurerType() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Собственик</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"insuredFirstName\" placeholder=\"Име\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"insuredSecondName\" placeholder=\"Презиме\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"insuredLastName\" placeholder=\"Фамилия\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>ЕГН</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"EGN\" placeholder=\"ЕГН\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Държава</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									CountryDAO countries = new CountryDAOImpl();
									for(Country country : countries.listCountries()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(country.getCountry());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"address\">Адрес на собственика</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"address\" placeholder=\"гр. ж.к. ул. бл. вх. ет. ап.\" size=\"50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"pKod\">Пощенски код</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"pKod\" placeholder=\"Пощенски код\" size=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Мобилен телефон</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"mobilePhone\" placeholder=\"Мобилен телефон\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-action\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Данни за МПС</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"registrationNumber\">Регистрационен №</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"registrationNumber\" placeholder=\"Регистрационен №\" size=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"zone\">Зона</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"zone\" class=\"field\" name=\"zone\" onchange=\"sum();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Зона І - София</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Зона IІ - Пловдив, Варна и Бургас</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Зона ІІІ - Други</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"vehicleType\">Вид МПС</label>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<select id=\"vehicleType\" class=\"field\" name=\"vehicleType\" onchange=\"change();\" ></select> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"vehicleType\" class=\"field\" name=\"vehicleType\" onchange=\"change();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											VehicleTypeDAO vTypes = new VehicleTypeDAOImpl();
											for(VehicleType type : vTypes.listVehicleTypes()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(type.getVehicleType() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"kubici\">Кубици</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"kubici\" class=\"field\" name=\"kubici\" onchange=\"sum();\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"ramaN\">Рама №</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"ramaN\" placeholder=\"Рама №\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"vehicleBrand\">Марка</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"vehicleBrand\" class=\"field\" name=\"vehicleBrand\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							   		VehicleBrandDAO brands = new VehicleBrandDAOImpl();
									for(VehicleBrand brand : brands.listAllVehicleBrand()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(brand.getVehicleBrand() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Модел</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"field\" name=\"vehicleModel\" placeholder=\"Модел\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Дата на сключване</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Начало</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" placeholder=\"Начална дата\" id=\"datepicker1\" name=\"fromDate\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Край</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" placeholder=\"Крайна датва\" id=\"datepicker2\" name=\"toDate\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("<!-- \t\t\t\t\t\t<div class=\"form-row\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<label>Срок</label> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<select id=\"months\" class=\"field\" name=\"months\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<option>3 месеца</option> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<option>6 месеца</option> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<option>12 месеца</option> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</select> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-action\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Застрахователна сума</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Застрахоателна сума</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"field\" id=\"vehicleInsValue\" name=\"vehicleInsValue\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Отстъпки</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" name=\"insOtstapki\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Надбавки</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" name=\"insNadbavki\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Застрахователна премия</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"field\" type=\"text\" name=\"insPremiq\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Сключи застраховка\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
